apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore-db
spec:
  replicas: 1
  selector:
    matchLabels:        # CORREÇÃO 1: "Labels" (el) e não "Lables" (le)
      app: metastore-db
  template:
    metadata:
      labels:
        app: metastore-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lakehouse-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage
      volumes:
      - name: db-storage
        hostPath:
          path: /home/andre/lakehouse_data_postgres
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: metastore-service
spec:
  type: NodePort
  selector:
    app: metastore-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 30054
